version: "3.5"

services:
  mongo-db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: lapis
      MONGO_INITDB_ROOT_PASSWORD: lapis
    ports:
      - 27017:27017

  # lib-gces:
  #   build: .
  #   depends_on:
  #     - mongo-db

  metabase:
    image: metabase/metabase
    ports:
      - 3000:3000
