name: Build and deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
          docker-compose up -d
      
      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build 
        run: poetry build -v

      - name: Publish
        run: |  
          poetry config pypi-token.pypi ${{ secrets.TOKEN }}
          poetry publish --username __token__ -v