name: Documentation

on:
  push:
    branches: [master]

jobs:
  documentation:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install python and pip
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependecies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get install doxygen
        pip install breathe
        pip install sphinx
        pip install sphinx_autodoc_typehints
        
    - name: Rodando sphinx
      working-directory: ./docs
      run: |
        make html
